variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "max_size" {}
variable "min_size" {}
variable "instance_type" {}
variable "bucket_name_1" {}
variable "bucket_name_2" {}
variable "bucket_name_3" {}
